package org.example.enumiration;

public enum TypeOfMajor {
    KARSHENASIPEYVASTE,
    KARSHENASINAPEVASTE,
    KRDANI,
    KARSHENASIARSHADPEYVASTE,
    KARSHENASIARSHADNAPEYVASTE,
    DOKTORAHERFEE,
    DOKTORAPEYVASTE,
    DOKTORANAPEVASTE
}
